// <auto-generated />
using System;
using InfoedukaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoedukaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521194939_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoedukaApi.Models.Kolegij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kolegiji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Projektni Razvoj Aplikacija",
                            Opis = "Kolegij o razvoju aplikacija"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Baze Podataka",
                            Opis = "Kolegij o bazama podataka"
                        });
                });

            modelBuilder.Entity("InfoedukaApi.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@infoeduka.hr",
                            Ime = "Admin",
                            Lozinka = "$2a$11$1pyL3mPQImM3.nF5m9eyl.buUnI4g65QO/ySfbNRMQ9E6r2XpfkKe",
                            Prezime = "Admin",
                            Tip = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivan@infoeduka.hr",
                            Ime = "Ivan",
                            Lozinka = "$2a$11$oYERp7IfqIS3gb/bti4uqei8zeaNm/KQcZ3FCciuYxuzldwGNoftK",
                            Prezime = "Ivić",
                            Tip = "Predavac"
                        });
                });

            modelBuilder.Entity("InfoedukaApi.Models.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("KolegijId")
                        .HasColumnType("int");

                    b.Property<int>("KreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KolegijId");

                    b.HasIndex("KreatorId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("KolegijKorisnik", b =>
                {
                    b.Property<int>("KolegijiId")
                        .HasColumnType("int");

                    b.Property<int>("PredavaciId")
                        .HasColumnType("int");

                    b.HasKey("KolegijiId", "PredavaciId");

                    b.HasIndex("PredavaciId");

                    b.ToTable("KolegijPredavac", (string)null);

                    b.HasData(
                        new
                        {
                            KolegijiId = 1,
                            PredavaciId = 2
                        });
                });

            modelBuilder.Entity("InfoedukaApi.Models.Obavijest", b =>
                {
                    b.HasOne("InfoedukaApi.Models.Kolegij", "Kolegij")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KolegijId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoedukaApi.Models.Korisnik", "Kreator")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kolegij");

                    b.Navigation("Kreator");
                });

            modelBuilder.Entity("KolegijKorisnik", b =>
                {
                    b.HasOne("InfoedukaApi.Models.Kolegij", null)
                        .WithMany()
                        .HasForeignKey("KolegijiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoedukaApi.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("PredavaciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoedukaApi.Models.Kolegij", b =>
                {
                    b.Navigation("Obavijesti");
                });

            modelBuilder.Entity("InfoedukaApi.Models.Korisnik", b =>
                {
                    b.Navigation("Obavijesti");
                });
#pragma warning restore 612, 618
        }
    }
}
