// <auto-generated />
using System;
using InfoedukaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoedukaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfoedukaApi.Models.Kolegij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kolegiji");
                });

            modelBuilder.Entity("InfoedukaApi.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@infoeduka.hr",
                            Ime = "Admin",
                            Lozinka = "$2a$11$PttD8PK/rViiotbTyPt0OOSsWO4kMS11R4jiWH3iMVWlThTFOK/IS",
                            Prezime = "Admin",
                            Tip = "Admin"
                        });
                });

            modelBuilder.Entity("InfoedukaApi.Models.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<int>("KolegijId")
                        .HasColumnType("int");

                    b.Property<int>("KreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KolegijId");

                    b.HasIndex("KreatorId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("KolegijKorisnik", b =>
                {
                    b.Property<int>("KolegijiId")
                        .HasColumnType("int");

                    b.Property<int>("PredavaciId")
                        .HasColumnType("int");

                    b.HasKey("KolegijiId", "PredavaciId");

                    b.HasIndex("PredavaciId");

                    b.ToTable("KolegijPredavac", (string)null);
                });

            modelBuilder.Entity("InfoedukaApi.Models.Obavijest", b =>
                {
                    b.HasOne("InfoedukaApi.Models.Kolegij", "Kolegij")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KolegijId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoedukaApi.Models.Korisnik", "Kreator")
                        .WithMany("Obavijesti")
                        .HasForeignKey("KreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kolegij");

                    b.Navigation("Kreator");
                });

            modelBuilder.Entity("KolegijKorisnik", b =>
                {
                    b.HasOne("InfoedukaApi.Models.Kolegij", null)
                        .WithMany()
                        .HasForeignKey("KolegijiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfoedukaApi.Models.Korisnik", null)
                        .WithMany()
                        .HasForeignKey("PredavaciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoedukaApi.Models.Kolegij", b =>
                {
                    b.Navigation("Obavijesti");
                });

            modelBuilder.Entity("InfoedukaApi.Models.Korisnik", b =>
                {
                    b.Navigation("Obavijesti");
                });
#pragma warning restore 612, 618
        }
    }
}
